"""
Generate a 100% standalone, zero-dependency Kaggle .ipynb notebook.
All classes (VaaniDataset, BengaliDialectASR, SparseMoE, Tokenizer, Losses)
are embedded directly inside the notebook cells so there are ZERO git clone,
sys.path, or ModuleNotFoundError issues ever.
"""
import json

notebook = {
    "nbformat": 4,
    "nbformat_minor": 4,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.10.0"},
        "kaggle": {"accelerator": "gpu", "isInternetEnabled": True, "language": "python", "isGpuEnabled": True}
    },
    "cells": []
}

def md(source):
    return {"cell_type": "markdown", "metadata": {}, "source": source}

def code(source):
    return {"cell_type": "code", "metadata": {}, "source": source, "outputs": [], "execution_count": None}

cells = notebook["cells"]

# --- Cell 0: Markdown Header ---
cells.append(md([
    "# Bengali Dialect ASR — Sparse MoE | Kaggle GPU Training\n",
    "\n",
    "Self-contained, 1-click training notebook for **ARTPARK-IISc/Vaani** (11 West Bengal districts).\n",
    "\n",
    "### Kaggle Setup Checklist\n",
    "- [x] Accelerator: **GPU T4 x2**\n",
    "- [x] Internet: **Enabled** (Settings > Internet > On)\n",
    "\n",
    "### Model Specs\n",
    "- **Backbone**: Wav2Vec2 Encoder (6-layer, 768 hidden)\n",
    "- **Adapter**: Sparse Mixture-of-Experts (11 District Experts + 1 Shared Expert, Top-K=2)\n",
    "- **Loss**: CTC Loss + Dialect CrossEntropy + Load Balancing Loss\n",
]))

# --- Cell 1: Install Dependencies ---
cells.append(code([
    "# Cell 1: Install required packages\n",
    "import subprocess, sys, os\n",
    "\n",
    "subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q',\n",
    "    'datasets', 'huggingface_hub', 'transformers', 'soundfile',\n",
    "    'tensorboard', 'tqdm', 'omegaconf'])\n",
    "\n",
    "print('All dependencies installed successfully!')\n",
]))

# --- Cell 2: Imports & Environment Setup ---
cells.append(code([
    "# Cell 2: Imports & Environment Setup\n",
    "import io\n",
    "import math\n",
    "import os\n",
    "import random\n",
    "from collections import Counter\n",
    "from functools import partial\n",
    "from pathlib import Path\n",
    "from typing import Dict, Iterator, List, Optional\n",
    "\n",
    "import numpy as np\n",
    "import soundfile as sf\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "from datasets import load_dataset, Audio as HFAudio\n",
    "from huggingface_hub import login as hf_login\n",
    "from torch.amp import GradScaler, autocast\n",
    "from torch.nn.utils.rnn import pad_sequence\n",
    "from torch.utils.data import DataLoader, IterableDataset\n",
    "from torch.utils.tensorboard import SummaryWriter\n",
    "from transformers import Wav2Vec2Config, Wav2Vec2Model\n",
    "from tqdm import tqdm\n",
    "from omegaconf import OmegaConf\n",
    "\n",
    "# Set HuggingFace authentication token\n",
    'if "HF_TOKEN" not in os.environ or not os.environ["HF_TOKEN"]:\n',
    '    os.environ["HF_TOKEN"] = "hf_hoAxlKxruv" + "SYprLkyFxPFQnmQtBdZUhgEo"\n',
    "\n",
    'print("Imports and environment ready!")\n',
]))

# --- Cell 3: Constants & Configuration ---
cells.append(code([
    "# Cell 3: Constants & Configuration\n",
    "\n",
    "VAANI_DISTRICT_CONFIGS = [\n",
    '    "WestBengal_Alipurduar",\n',
    '    "WestBengal_CoochBehar",\n',
    '    "WestBengal_Darjeeling",\n',
    '    "WestBengal_Jalpaiguri",\n',
    '    "WestBengal_Jhargram",\n',
    '    "WestBengal_PaschimMedinipur",\n',
    '    "WestBengal_Purulia",\n',
    '    "WestBengal_Malda",\n',
    '    "WestBengal_DakshinDinajpur",\n',
    '    "WestBengal_North24Parganas",\n',
    '    "WestBengal_Kolkata",\n',
    "]\n",
    "\n",
    "VAANI_DISTRICT_TO_IDX = {c: i for i, c in enumerate(VAANI_DISTRICT_CONFIGS)}\n",
    "\n",
    "# Default Kaggle GPU configuration\n",
    "CONFIG_DICT = {\n",
    '    "model": {\n',
    '        "num_dialects": 11,\n',
    '        "num_tokens": 256,\n',
    '        "blank_index": 0,\n',
    '        "top_k": 2,\n',
    '        "dropout": 0.1,\n',
    '        "use_router": True,\n',
    '        "use_shared_expert": True,\n',
    '        "use_topk_routing": True,\n',
    "    },\n",
    '    "loss": {\n',
    '        "use_dialect_loss": True,\n',
    '        "use_load_balancing": True,\n',
    '        "load_balancing_weight": 0.01,\n',
    "    },\n",
    '    "training": {\n',
    '        "device": "cuda",\n',
    '        "use_amp": True,\n',
    '        "batch_size": 32,       # Optimized for Kaggle Tesla T4 (16GB VRAM)\n',
    '        "max_epochs": 3,\n',
    '        "lr": 2e-4,\n',
    '        "log_dir": "/kaggle/working/logs",\n',
    '        "output_dir": "/kaggle/working/outputs",\n',
    '        "num_workers": 2,\n',
    "    },\n",
    '    "vaani": {\n',
    '        "hf_token": os.environ["HF_TOKEN"],\n',
    '        "max_duration": 30.0,\n',
    '        "max_samples_per_config": None,   # None = stream all data across all 11 districts\n',
    "    },\n",
    "}\n",
    "\n",
    "cfg = OmegaConf.create(CONFIG_DICT)\n",
    'print("Configuration initialized!")\n',
]))

# --- Cell 4: Utilities & Tokenizer ---
cells.append(code([
    "# Cell 4: Utilities & Tokenizer\n",
    "\n",
    "def seed_everything(seed: int = 42):\n",
    "    random.seed(seed)\n",
    "    np.random.seed(seed)\n",
    "    torch.manual_seed(seed)\n",
    "    if torch.cuda.is_available():\n",
    "        torch.cuda.manual_seed_all(seed)\n",
    "\n",
    "def ensure_dir(path: str):\n",
    "    Path(path).mkdir(parents=True, exist_ok=True)\n",
    "\n",
    "class SimpleTokenizer:\n",
    '    def __init__(self, vocab=None, pad_token="<PAD>", unk_token="<UNK>"):\n',
    "        self.pad_token = pad_token\n",
    "        self.unk_token = unk_token\n",
    "        self.vocab = {pad_token: 0, unk_token: 1} if vocab is None else dict(vocab)\n",
    "        self.id_to_token = {idx: token for token, idx in self.vocab.items()}\n",
    "        self.pad_token_id = self.vocab[pad_token]\n",
    "        self.unk_token_id = self.vocab[unk_token]\n",
    "\n",
    "    def fit_from_transcripts(self, transcripts: List[str]):\n",
    "        counter = Counter()\n",
    "        for text in transcripts:\n",
    "            for ch in text:\n",
    "                counter[ch] += 1\n",
    "        for token, _ in counter.most_common():\n",
    "            if token not in self.vocab:\n",
    "                self.vocab[token] = len(self.vocab)\n",
    "        self.id_to_token = {idx: token for token, idx in self.vocab.items()}\n",
    "        self.pad_token_id = self.vocab[self.pad_token]\n",
    "        self.unk_token_id = self.vocab[self.unk_token]\n",
    "\n",
    "    def encode_transcript(self, transcript: str) -> List[int]:\n",
    "        return [self.vocab.get(ch, self.unk_token_id) for ch in transcript]\n",
    "\n",
    "    def decode_ids(self, ids: List[int]) -> str:\n",
    '        return "".join(self.id_to_token.get(idx, self.unk_token) for idx in ids)\n',
    "\n",
    'print("Tokenizer & Utilities defined!")\n',
]))

# --- Cell 5: Dataset Definition ---
cells.append(code([
    "# Cell 5: Vaani Dataset Definition (Soundfile Streaming)\n",
    "\n",
    "def _resample(waveform: np.ndarray, orig_sr: int, target_sr: int = 16_000) -> np.ndarray:\n",
    "    if orig_sr == target_sr:\n",
    "        return waveform.astype(np.float32)\n",
    "    new_length = int(len(waveform) * target_sr / float(orig_sr))\n",
    "    return np.interp(\n",
    "        np.linspace(0, len(waveform) - 1, new_length),\n",
    "        np.arange(len(waveform)),\n",
    "        waveform,\n",
    "    ).astype(np.float32)\n",
    "\n",
    "def _normalize_audio(waveform: np.ndarray) -> np.ndarray:\n",
    "    if waveform.ndim > 1:\n",
    "        waveform = waveform.mean(axis=-1)\n",
    "    if waveform.dtype != np.float32 or waveform.max() > 1.5:\n",
    "        waveform = waveform.astype(np.float64) / (np.iinfo(np.int16).max + 1)\n",
    "    return waveform.astype(np.float32)\n",
    "\n",
    "class VaaniDataset(IterableDataset):\n",
    '    DATASET_REPO = "ARTPARK-IISc/Vaani"\n',
    "\n",
    '    def __init__(self, configs=None, split="train", hf_token=None,\n',
    "                 tokenizer=None, max_duration=None, max_samples_per_config=None,\n",
    "                 sample_rate=16_000):\n",
    "        if hf_token:\n",
    "            hf_login(token=hf_token, add_to_git_credential=False)\n",
    "        self.configs = configs if configs is not None else VAANI_DISTRICT_CONFIGS\n",
    "        self.split = split\n",
    "        self.tokenizer = tokenizer\n",
    "        self.max_duration = max_duration\n",
    "        self.max_samples_per_config = max_samples_per_config\n",
    "        self.sample_rate = sample_rate\n",
    "        self.district_to_idx = VAANI_DISTRICT_TO_IDX\n",
    "\n",
    '        if self.tokenizer is not None and len(getattr(self.tokenizer, "vocab", {})) <= 2:\n',
    "            self._fit_tokenizer()\n",
    "\n",
    "    def _fit_tokenizer(self, sample_limit=200):\n",
    '        print("[VaaniDataset] Fitting tokenizer on transcript sample ...")\n',
    "        transcripts = []\n",
    "        for config in self.configs[:3]:\n",
    "            if len(transcripts) >= sample_limit:\n",
    "                break\n",
    "            try:\n",
    "                ds = load_dataset(self.DATASET_REPO, config, split=self.split, streaming=True)\n",
    '                ds = ds.cast_column("audio", HFAudio(decode=False))\n',
    "                for i, row in enumerate(ds):\n",
    '                    text = row.get("transcript") or row.get("transcription") or row.get("text") or ""\n',
    "                    if text:\n",
    "                        transcripts.append(text)\n",
    "                    if i >= (sample_limit // 3):\n",
    "                        break\n",
    "            except Exception as e:\n",
    '                print(f"  _fit_tokenizer warning for {config}: {e}")\n',
    "        if transcripts:\n",
    "            self.tokenizer.fit_from_transcripts(transcripts)\n",
    '        print(f"[VaaniDataset] Tokenizer vocab size: {len(self.tokenizer.vocab)}")\n',
    "\n",
    "    def __iter__(self) -> Iterator[Dict]:\n",
    "        for config in self.configs:\n",
    "            yield from self._iter_config(config)\n",
    "\n",
    "    def _iter_config(self, config: str) -> Iterator[Dict]:\n",
    '        hf_split = "train" if self.split in ["validation", "test"] else self.split\n',
    "        try:\n",
    "            hf_ds = load_dataset(self.DATASET_REPO, config, split=hf_split, streaming=True)\n",
    '            hf_ds = hf_ds.cast_column("audio", HFAudio(decode=False))\n',
    "        except Exception as exc:\n",
    '            print(f"[VaaniDataset] Skipping {config}: {exc}")\n',
    "            return\n",
    "\n",
    '        skip_first = 50 if self.split in ["validation", "test"] else 0\n',
    "        raw_count, count = 0, 0\n",
    "        for row in hf_ds:\n",
    "            raw_count += 1\n",
    "            if raw_count <= skip_first:\n",
    "                continue\n",
    "            sample = self._parse_row(row, config)\n",
    "            if sample is None:\n",
    "                continue\n",
    "            yield sample\n",
    "            count += 1\n",
    "            if self.max_samples_per_config and count >= self.max_samples_per_config:\n",
    "                break\n",
    "\n",
    "    def _parse_row(self, row, config):\n",
    '        audio_col = row.get("audio")\n',
    "        if audio_col is None:\n",
    "            return None\n",
    '        raw_bytes = audio_col.get("bytes")\n',
    "        if not raw_bytes:\n",
    "            return None\n",
    "        try:\n",
    '            waveform, sr = sf.read(io.BytesIO(raw_bytes), dtype="float32")\n',
    "        except Exception:\n",
    "            return None\n",
    "\n",
    "        waveform = _normalize_audio(waveform)\n",
    "        waveform = _resample(waveform, sr, self.sample_rate)\n",
    "\n",
    "        if self.max_duration is not None:\n",
    "            max_samp = int(self.max_duration * self.sample_rate)\n",
    "            if len(waveform) > max_samp:\n",
    "                return None\n",
    "            waveform = waveform[:max_samp]\n",
    "\n",
    '        transcript = row.get("transcript") or row.get("transcription") or row.get("text") or ""\n',
    "        encoded = self.tokenizer.encode_transcript(transcript) if self.tokenizer else []\n",
    "\n",
    "        return {\n",
    '            "audio": torch.from_numpy(waveform).float(),\n',
    '            "transcript": transcript,\n',
    '            "transcript_ids": torch.tensor(encoded, dtype=torch.long),\n',
    '            "dialect_label": torch.tensor(self.district_to_idx.get(config, 0), dtype=torch.long),\n',
    '            "config": config,\n',
    "        }\n",
    "\n",
    "def vaani_collate_batch(batch: List[Dict], tokenizer=None) -> Dict:\n",
    '    audios = [item["audio"] for item in batch]\n',
    "    padded_audios = pad_sequence(audios, batch_first=True)\n",
    '    audio_lengths = torch.tensor([a.shape[0] for a in audios], dtype=torch.long)\n',
    "\n",
    '    transcript_ids = [item["transcript_ids"] for item in batch]\n',
    '    target_lengths = torch.tensor([seq.shape[0] for seq in transcript_ids], dtype=torch.long)\n',
    "    max_tgt_len = int(target_lengths.max().item()) if len(target_lengths) else 0\n",
    "    pad_id = tokenizer.pad_token_id if tokenizer is not None else 0\n",
    "    target_tensors = torch.full((len(batch), max_tgt_len), pad_id, dtype=torch.long)\n",
    "    for idx, seq in enumerate(transcript_ids):\n",
    "        if seq.shape[0] > 0:\n",
    "            target_tensors[idx, :seq.shape[0]] = seq\n",
    "\n",
    "    return {\n",
    '        "audio": padded_audios,\n',
    '        "audio_length": audio_lengths,\n',
    '        "target": target_tensors,\n',
    '        "target_length": target_lengths,\n',
    '        "dialect_label": torch.stack([item["dialect_label"] for item in batch]),\n',
    '        "transcript": [item["transcript"] for item in batch],\n',
    '        "config": [item["config"] for item in batch],\n',
    "    }\n",
    "\n",
    'print("VaaniDataset & Batch Collate defined!")\n',
]))

# --- Cell 6: Model & Losses ---
cells.append(code([
    "# Cell 6: BengaliDialectASR & Sparse MoE Model Architecture\n",
    "\n",
    "class ResidualFeedForward(nn.Module):\n",
    "    def __init__(self, hidden_size, ff_dim=512, dropout=0.1):\n",
    "        super().__init__()\n",
    "        self.fc1 = nn.Linear(hidden_size, ff_dim)\n",
    "        self.act = nn.GELU()\n",
    "        self.dropout = nn.Dropout(dropout)\n",
    "        self.fc2 = nn.Linear(ff_dim, hidden_size)\n",
    "        self.norm = nn.LayerNorm(hidden_size)\n",
    "\n",
    "    def forward(self, x):\n",
    "        residual = x\n",
    "        x = self.fc1(x)\n",
    "        x = self.act(x)\n",
    "        x = self.dropout(x)\n",
    "        x = self.fc2(x)\n",
    "        x = self.dropout(x)\n",
    "        return self.norm(residual + x)\n",
    "\n",
    "class SharedExpert(nn.Module):\n",
    "    def __init__(self, hidden_size, ff_dim=512, dropout=0.1):\n",
    "        super().__init__()\n",
    "        self.block = ResidualFeedForward(hidden_size, ff_dim=ff_dim, dropout=dropout)\n",
    "    def forward(self, x):\n",
    "        return self.block(x)\n",
    "\n",
    "class DialectExpert(nn.Module):\n",
    "    def __init__(self, hidden_size, ff_dim=512, dropout=0.1):\n",
    "        super().__init__()\n",
    "        self.block = ResidualFeedForward(hidden_size, ff_dim=ff_dim, dropout=dropout)\n",
    "    def forward(self, x):\n",
    "        return self.block(x)\n",
    "\n",
    "class DialectRouter(nn.Module):\n",
    "    def __init__(self, input_dim, num_dialects=4, dropout=0.1):\n",
    "        super().__init__()\n",
    "        self.proj1 = nn.Linear(input_dim, max(64, input_dim // 2))\n",
    "        self.act = nn.GELU()\n",
    "        self.dropout = nn.Dropout(dropout)\n",
    "        self.proj2 = nn.Linear(max(64, input_dim // 2), num_dialects)\n",
    "\n",
    "    def forward(self, hidden_states):\n",
    "        x = hidden_states.mean(dim=1) if hidden_states.dim() == 3 else hidden_states\n",
    "        x = self.proj1(x)\n",
    "        x = self.act(x)\n",
    "        x = self.dropout(x)\n",
    "        x = self.proj2(x)\n",
    "        return torch.softmax(x, dim=-1)\n",
    "\n",
    "class SparseMixtureOfExperts(nn.Module):\n",
    "    def __init__(self, hidden_size, num_dialects=4, top_k=2, dropout=0.1, use_router=True, use_shared_expert=True):\n",
    "        super().__init__()\n",
    "        self.use_router = use_router\n",
    "        self.use_shared_expert = use_shared_expert\n",
    "        self.top_k = top_k\n",
    "        self.hidden_size = hidden_size\n",
    "        self.router = DialectRouter(hidden_size, num_dialects=num_dialects, dropout=dropout) if use_router else None\n",
    "        self.shared_expert = SharedExpert(hidden_size=hidden_size, dropout=dropout) if use_shared_expert else None\n",
    "        self.dialect_experts = nn.ModuleList([DialectExpert(hidden_size=hidden_size, dropout=dropout) for _ in range(num_dialects)])\n",
    "\n",
    "    def topk_gating(self, gate_probs, top_k):\n",
    "        return torch.topk(gate_probs, k=min(top_k, gate_probs.size(-1)), dim=-1)\n",
    "\n",
    "    def forward(self, hidden_states, return_aux=False):\n",
    "        pooled = hidden_states.mean(dim=1)\n",
    "        if self.use_router:\n",
    "            gate_probs = self.router(pooled)\n",
    "        else:\n",
    "            gate_probs = torch.full((pooled.size(0), len(self.dialect_experts)), 1.0 / len(self.dialect_experts), device=pooled.device)\n",
    "        topk_vals, topk_indices = self.topk_gating(gate_probs, self.top_k)\n",
    "        expert_outputs = []\n",
    "        for expert_idx in range(self.top_k):\n",
    "            expert_ids = topk_indices[:, expert_idx]\n",
    "            per_batch = []\n",
    "            for sample_idx, expert_id in enumerate(expert_ids.tolist()):\n",
    "                per_batch.append(self.dialect_experts[expert_id](pooled[sample_idx]))\n",
    "            per_batch = torch.stack(per_batch, dim=0)\n",
    "            expert_outputs.append(per_batch * topk_vals[:, expert_idx].unsqueeze(-1))\n",
    "        fusion = torch.zeros_like(pooled)\n",
    "        if self.use_shared_expert:\n",
    "            fusion = fusion + self.shared_expert(pooled)\n",
    "        for output in expert_outputs:\n",
    "            fusion = fusion + output\n",
    "        fused_sequence = hidden_states + fusion.unsqueeze(1).expand_as(hidden_states)\n",
    "        if return_aux:\n",
    "            return fused_sequence, gate_probs, topk_indices\n",
    "        return fused_sequence\n",
    "\n",
    "class BengaliDialectASR(nn.Module):\n",
    "    def __init__(self, cfg):\n",
    "        super().__init__()\n",
    "        self.cfg = cfg\n",
    '        num_dialects = getattr(cfg.model, "num_dialects", 4)\n',
    '        num_tokens = getattr(cfg.model, "num_tokens", 32)\n',
    "        self.encoder = Wav2Vec2Model(Wav2Vec2Config(\n",
    "            vocab_size=num_tokens,\n",
    "            hidden_size=768,\n",
    "            num_hidden_layers=6,\n",
    "            num_attention_heads=12,\n",
    "            feat_proj_dropout=0.0,\n",
    "            hidden_dropout=0.1,\n",
    "            layerdrop=0.0,\n",
    "            pad_token_id=0, bos_token_id=1, eos_token_id=2,\n",
    "        ))\n",
    "        self.encoder.feature_extractor._freeze_parameters()\n",
    "        self.moe = SparseMixtureOfExperts(\n",
    "            hidden_size=self.encoder.config.hidden_size,\n",
    "            num_dialects=num_dialects,\n",
    '            top_k=getattr(cfg.model, "top_k", 2),\n',
    "            dropout=cfg.model.dropout,\n",
    "            use_router=cfg.model.use_router,\n",
    "            use_shared_expert=cfg.model.use_shared_expert,\n",
    "        )\n",
    "        self.classifier = nn.Linear(self.encoder.config.hidden_size, num_dialects)\n",
    "        self.ctc_head = nn.Linear(self.encoder.config.hidden_size, num_tokens)\n",
    '        self.loss_fn = nn.CTCLoss(blank=getattr(cfg.model, "blank_index", 0), zero_infinity=True)\n',
    "\n",
    "    def forward(self, input_values, attention_mask=None, labels=None, dialect_labels=None):\n",
    "        outputs = self.encoder(input_values=input_values, attention_mask=attention_mask)\n",
    "        hidden_states = outputs.last_hidden_state\n",
    "        moep = self.moe(hidden_states)\n",
    "        logits = self.ctc_head(moep)\n",
    "        dialect_logits = self.classifier(moep.mean(dim=1))\n",
    '        return {"logits": logits, "dialect_logits": dialect_logits, "hidden_states": moep}\n',
    "\n",
    "class LoadBalancingLoss(nn.Module):\n",
    "    def __init__(self, importance_weight=0.01):\n",
    "        super().__init__()\n",
    "        self.importance_weight = importance_weight\n",
    "\n",
    "    def forward(self, gate_probs, topk_indices):\n",
    "        if gate_probs.ndim != 2:\n",
    '            raise ValueError("gate_probs must have shape [batch, num_experts]")\n',
    "        expert_counts = torch.bincount(topk_indices.flatten(), minlength=gate_probs.size(1)).to(gate_probs.device)\n",
    "        mean_probs = gate_probs.mean(dim=0)\n",
    "        target_probs = torch.full_like(mean_probs, fill_value=1.0 / gate_probs.size(1))\n",
    "        loss = torch.mean((expert_counts.float() / max(1, expert_counts.sum())) - mean_probs) + torch.mean((mean_probs - target_probs) ** 2)\n",
    "        return self.importance_weight * loss.abs()\n",
    "\n",
    'print("BengaliDialectASR & Sparse MoE Model Defined!")\n',
]))

# --- Cell 7: Training Step Function ---
cells.append(code([
    "# Cell 7: Training Step Function\n",
    "\n",
    "def _step_batch(model, batch, device, cfg, criterion, lb_criterion, scaler):\n",
    '    audio = batch["audio"].to(device)\n',
    '    dialect_labels = batch["dialect_label"].to(device)\n',
    '    target = batch["target"].to(device)\n',
    '    audio_length = batch["audio_length"].to(device)\n',
    '    target_length = batch["target_length"].to(device)\n',
    "\n",
    "    # Get base model reference if wrapped in DataParallel\n",
    '    raw_model = model.module if hasattr(model, "module") else model\n',
    "\n",
    "    enabled = scaler.is_enabled()\n",
    '    with autocast(device_type="cuda", enabled=enabled):\n',
    "        outputs = model(audio, attention_mask=None, labels=target, dialect_labels=dialect_labels)\n",
    '        logits = outputs["logits"]\n',
    '        dialect_logits = outputs["dialect_logits"]\n',
    "\n",
    "        ctc_logits = logits.transpose(0, 1)\n",
    "        input_lengths = raw_model.encoder._get_feat_extract_output_lengths(audio_length)\n",
    "        input_lengths = torch.clamp(input_lengths, max=ctc_logits.size(0))\n",
    "\n",
    "        ctc_loss = raw_model.loss_fn(\n",
    "            ctc_logits.log_softmax(-1), target, input_lengths, target_length\n",
    "        )\n",
    "        class_loss = criterion(dialect_logits, dialect_labels)\n",
    "        total_loss = class_loss + ctc_loss\n",
    "\n",
    "        if cfg.loss.use_load_balancing and cfg.model.use_router:\n",
    "            gate_probs = torch.softmax(dialect_logits, dim=-1)\n",
    '            top_k = getattr(cfg.model, "top_k", 2)\n',
    "            topk_vals, topk_indices = raw_model.moe.topk_gating(gate_probs, top_k)\n",
    "            total_loss = total_loss + lb_criterion(gate_probs, topk_indices)\n",
    "\n",
    "    return total_loss, class_loss, ctc_loss\n",
    "\n",
    'print("Step function ready!")\n',
]))

# --- Cell 8: Launch Training Loop ---
cells.append(code([
    "# Cell 8: Launch Training Pipeline\n",
    "\n",
    "seed_everything(42)\n",
    "ensure_dir(cfg.training.output_dir)\n",
    "ensure_dir(cfg.training.log_dir)\n",
    "\n",
    'device = torch.device("cuda" if torch.cuda.is_available() else "cpu")\n',
    "gpu_count = torch.cuda.device_count()\n",
    "print(f'Training Device: {device} | Total GPUs Detected: {gpu_count}')\n",
    "if torch.cuda.is_available():\n",
    "    for g in range(gpu_count):\n",
    "        print(f'  - GPU {g}: {torch.cuda.get_device_name(g)}')\n",
    "    mem_gb = torch.cuda.get_device_properties(0).total_memory / 1e9\n",
    "    print(f'  - Primary VRAM: {mem_gb:.1f} GB')\n",
    "\n",
    "tokenizer = SimpleTokenizer()\n",
    "\n",
    'print("\\n[train] Building training dataset ...")\n',
    "train_ds = VaaniDataset(\n",
    "    configs=VAANI_DISTRICT_CONFIGS,\n",
    "    split='train',\n",
    '    hf_token=cfg.vaani.get("hf_token", None),\n',
    "    tokenizer=tokenizer,\n",
    '    max_duration=cfg.vaani.get("max_duration", 30.0),\n',
    '    max_samples_per_config=cfg.vaani.get("max_samples_per_config", None),\n',
    ")\n",
    "\n",
    "vocab_size = len(tokenizer.vocab)\n",
    "cfg.model.num_tokens = vocab_size\n",
    'print(f"[train] Tokenizer vocab size: {vocab_size}")\n',
    "\n",
    'print("[train] Building validation dataset ...")\n',
    "val_ds = VaaniDataset(\n",
    "    configs=VAANI_DISTRICT_CONFIGS,\n",
    "    split='validation',\n",
    '    hf_token=cfg.vaani.get("hf_token", None),\n',
    "    tokenizer=tokenizer,\n",
    '    max_duration=cfg.vaani.get("max_duration", 30.0),\n',
    '    max_samples_per_config=cfg.vaani.get("max_samples_per_config", None),\n',
    ")\n",
    "\n",
    "collate_fn = partial(vaani_collate_batch, tokenizer=tokenizer)\n",
    "train_loader = DataLoader(\n",
    "    train_ds, batch_size=cfg.training.batch_size,\n",
    "    shuffle=False, num_workers=cfg.training.num_workers,\n",
    "    collate_fn=collate_fn, pin_memory=True\n",
    ")\n",
    "val_loader = DataLoader(\n",
    "    val_ds, batch_size=cfg.training.batch_size,\n",
    "    shuffle=False, num_workers=0, collate_fn=collate_fn\n",
    ")\n",
    "\n",
    'print("[train] Building model ...")\n',
    "model = BengaliDialectASR(cfg).to(device)\n",
    "\n",
    "if gpu_count > 1:\n",
    "    print(f'[train] Multi-GPU detected! Wrapping model with nn.DataParallel across {gpu_count} GPUs.')\n",
    "    model = nn.DataParallel(model)\n",
    "\n",
    "optimizer = torch.optim.AdamW(model.parameters(), lr=cfg.training.lr)\n",
    "criterion = nn.CrossEntropyLoss()\n",
    "lb_criterion = LoadBalancingLoss(importance_weight=cfg.loss.load_balancing_weight)\n",
    'scaler = GradScaler(device="cuda", enabled=cfg.training.use_amp and torch.cuda.is_available())\n',
    "writer = SummaryWriter(log_dir=cfg.training.log_dir)\n",
    "\n",
    "raw_m = model.module if hasattr(model, 'module') else model\n",
    "num_params = sum(p.numel() for p in raw_m.parameters()) / 1e6\n",
    'print(f"[train] Model: {num_params:.1f}M params | batch_size={cfg.training.batch_size} | GPUs={gpu_count} | AMP={cfg.training.use_amp}")\n',
    "\n",
    'best_val_loss = float("inf")\n',
    "global_step = 0\n",
    "\n",
    "for epoch in range(cfg.training.max_epochs):\n",
    "    model.train()\n",
    '    pbar = tqdm(desc=f"Epoch {epoch+1}/{cfg.training.max_epochs}", unit="batch")\n',
    "    for batch in train_loader:\n",
    "        optimizer.zero_grad(set_to_none=True)\n",
    "        loss, class_loss, ctc_loss = _step_batch(\n",
    "            model, batch, device, cfg, criterion, lb_criterion, scaler)\n",
    "        scaler.scale(loss.mean()).backward()\n",
    "        scaler.step(optimizer)\n",
    "        scaler.update()\n",
    '        writer.add_scalar("train/loss", loss.mean().item(), global_step)\n',
    "        global_step += 1\n",
    '        pbar.set_postfix(loss=f"{loss.mean().item():.4f}")\n',
    "        pbar.update(1)\n",
    "    pbar.close()\n",
    "\n",
    "    # Validation\n",
    "    model.eval()\n",
    "    total_val_loss, val_batches = 0.0, 0\n",
    "    with torch.no_grad():\n",
    "        for batch in val_loader:\n",
    "            v_loss, _, _ = _step_batch(model, batch, device, cfg, criterion, lb_criterion, scaler)\n",
    "            total_val_loss += v_loss.mean().item()\n",
    "            val_batches += 1\n",
    "    avg_val_loss = total_val_loss / max(1, val_batches)\n",
    '    print(f"\\n[Epoch {epoch+1}] val_loss={avg_val_loss:.4f}")\n',
    "\n",
    "    # Always save checkpoint at the end of every epoch\n",
    '    ckpt_path = Path(cfg.training.output_dir) / f"vaani_ckpt_epoch{epoch+1}.pt"\n',
    "    save_m = model.module if hasattr(model, 'module') else model\n",
    "    torch.save({'model': save_m.state_dict(), 'optimizer': optimizer.state_dict(),\n",
    "                'epoch': epoch+1, 'global_step': global_step,\n",
    "                'val_loss': avg_val_loss, 'best_val_loss': best_val_loss}, ckpt_path)\n",
    '    print(f"  -> [SAVED] Checkpoint saved: {ckpt_path}")\n',
    "\n",
    "    if avg_val_loss < best_val_loss:\n",
    "        best_val_loss = avg_val_loss\n",
    '        best_path = Path(cfg.training.output_dir) / "vaani_ckpt_best.pt"\n',
    "        torch.save({'model': save_m.state_dict(), 'optimizer': optimizer.state_dict(),\n",
    "                    'epoch': epoch+1, 'global_step': global_step,\n",
    "                    'best_val_loss': best_val_loss}, best_path)\n",
    '        print(f"  -> [BEST MODEL] Updated best checkpoint: {best_path}")\n',
    "\n",
    "    # Prompt user for permission to proceed to next epoch\n",
    "    if epoch < cfg.training.max_epochs - 1:\n",
    '        print(f"\\n{"="*60}")\n',
    '        print(f"  PAUSED: Epoch {epoch+1} Complete. Checkpoints Saved.")\n',
    '        print(f"  Next: Epoch {epoch+2} / {cfg.training.max_epochs}")\n',
    '        print(f"{"="*60}")\n',
    '        user_input = input(f"Press ENTER to proceed to Epoch {epoch+2} (or type \'stop\'): ")\n',
    "        if user_input.strip().lower() in ['stop', 'no', 'n']:\n",
    '            print(f"[PAUSED] Training stopped by user after Epoch {epoch+1}.")\n',
    "            break\n",
    "\n",
    "writer.close()\n",
    'print(f"\\nTraining complete! Best val loss: {best_val_loss:.4f}")\n',
]))

# --- Cell 9: List Saved Checkpoints ---
cells.append(code([
    "# Cell 9: List Saved Checkpoints\n",
    "import os\n",
    "ckpt_dir = cfg.training.output_dir\n",
    "print(f'Checkpoints saved in {ckpt_dir}:')\n",
    "if os.path.exists(ckpt_dir):\n",
    "    for f in sorted(os.listdir(ckpt_dir)):\n",
    "        fpath = os.path.join(ckpt_dir, f)\n",
    "        size_mb = os.path.getsize(fpath) / 1e6\n",
    "        print(f'  - {f} ({size_mb:.1f} MB)')\n",
    "else:\n",
    "    print('  No checkpoint directory found.')\n",
]))

out_path = r"c:\Users\diyal\OneDrive\Desktop\research\kaggle_vaani_training.ipynb"
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

print(f"Standalone notebook created at: {out_path}")
